language: java

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 17.0.5-oracle
  - sdk use java 17.0.5-oracle

install:
  - mvn install -DskipTests=true -Dgpg.skip=true

dist: trusty

after_success:
  - mvn test jacoco:report coveralls:report
